### PR TITLE
Fix multi region no info

### PR DESCRIPTION
**Pull request by elagarrigue**
### What's new in this PR?
- Fix issue https://redmine.buzzhives.com/issues/10104

### CODE REVIEW

**Comment by thuutin** [comment]
@emmlagarrigue Can you explain what do you fix in this PR? What is the reason for "iOS shows route Android shows blank routes screen. Finland" ?

**Comment by elagarrigue** [comment]
@thuutin , the problem was that, in `routeAsync`, before calling routing.json we need to check if the region supports wheelchair information, in order to send the wheelchair preference or not. When the query had an origin-destination from different regions, the "region name" in the query is composed with both region names. Then, calling regionInfo.json retrieve no result, finishing the stream. 
The solution was not tu use the query region name, but get the region for each location and get each region info.

**Comment by elagarrigue** [comment]
Here is the related comment https://redmine.buzzhives.com/issues/10398#note-3

**Comment by thuutin** [comment]
@emmlagarrigue Which base url do you use to hit `routing.json`?

**Comment by elagarrigue** [comment]
That's query generation logic, I'll check.

**Comment by thuutin** [comment]
@emmlagarrigue Thanks.

**Comment by elagarrigue** [comment]
@thuutin , that logic resides on public `com.skedgo.android.common.model.Regions.createInterRegion()`. A region object is created, were:
- Region name is `departureRegion.getName() + "_" + arrivalRegion.getName()` (because of this we had the regionInfo as empty result).
- Transport modes are the union of both regions modes.
- Urls are departure region urls.
- Timezone is departure timezone

@nighthawk , can you confirm that this is the correct behaviour?

**Comment by nighthawk** [comment]
That's fine except TimeZone. You shouldn't really use the time zone of that combined region, but rather, when displaying times, use the time zones of the location for which you're displaying times. So if you have a trip going from `AU_WA_Perth` to `AU_NSW_Sydney` the departure time should be listed as Perth local time and the arrival time as Sydney local time (not Perth time).

**Comment by elagarrigue** [comment]
Right. Anyway, this region is created for the query, so in this case the departure time zone is the one sent to routing.json.

**Comment by thuutin** [comment]
@nighthawk Can you help us with an example of 2 regions where routing is supported and have different timezone? 
@elagarrigue Have you tested that the app is displaying times correctly?

**Comment by elagarrigue** [comment]
@thuutin , I could not find a way to test it, all inter regional trips I could find were in the same timezone. Anyway, we should create a new ticket about it, as this resolve the current "no results" issue.

**Comment by nighthawk** [comment]
We used to have long-distance flights in TripGo, which were great for testing this, but we don't currently. So I don't have a good test case, sorry.

**Pull request closed without merging**
